# Generated by Django 2.1.5 on 2020-02-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('hire_date', models.DateTimeField()),
                ('phone', models.CharField(default=False, max_length=20)),
                ('email', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
